CREATE DATABASE chat-api-db;
USE chat-api-db;
DROP TABLE IF EXISTS `Messages`;

CREATE TABLE `Messages` (
  `MESSAGE_ID` int(255) unsigned NOT NULL AUTO_INCREMENT,
  `FROM_USER_ID` int(255) unsigned NOT NULL,
  `TO_USER_ID` int(255) unsigned NOT NULL,
  `MESSAGE_TIMESTAMP` timestamp NULL DEFAULT current_timestamp(),
  `MESSAGE_SEEN` tinyint(1) unsigned DEFAULT 0,
  `MESSAGE_TEXT` text NOT NULL,
  PRIMARY KEY (`MESSAGE_ID`),
  KEY `BY_USER` (`FROM_USER_ID`,`TO_USER_ID`,`MESSAGE_TIMESTAMP`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `Sessions`;

CREATE TABLE `Sessions` (
  `USER_ID` int(255) unsigned NOT NULL,
  `SOCKET_ID` varchar(100) NOT NULL DEFAULT '',
  `SESSION_TOKEN` varchar(100) DEFAULT NULL,
  `SESSION_STARTED` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  UNIQUE KEY `ONE_SESSION_ID` (`SOCKET_ID`),
  KEY `BY_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `Users`;

CREATE TABLE `Users` (
  `USER_ID` int(255) unsigned NOT NULL AUTO_INCREMENT,
  `USER_LOGIN` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `ONE_LOGIN` (`USER_LOGIN`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;
